import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { TooltipProvider } from "@/components/ui/tooltip";
import { AuthProvider } from '@descope/nextjs-sdk';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



export default function RootLayout({ children }: LayoutProps<"/">) {
  // Get the Descope project ID from environment variables
  const descopeProjectId = process.env.NEXT_PUBLIC_DESCOPE_PROJECT_ID || "";

  // Define cookie options for session and refresh tokens
  const cookieOptions = {
    sameSite: "Lax" as const,
    secure: process.env.NODE_ENV === "production",
  }

  return (
    <AuthProvider projectId={descopeProjectId} sessionTokenViaCookie={cookieOptions} refreshTokenViaCookie={cookieOptions}>
      <html
        lang="en"
        className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
      >
        <body className="min-h-full flex flex-col">
          <TooltipProvider>
            {children}
          </TooltipProvider>
        </body>
      </html>
    </AuthProvider>
  );
}
